Repository zowe/imperative, pull requests merged in 2018-10, with the labels that each got.

#32 Fix/19
  packages/rest/src/session/AbstractSession.ts
  packages/utilities/__tests__/JSONUtils.test.ts
  packages/utilities/src/JSONUtils.ts
Labels: Patch, bug, in progress, review

#65 Enhancement/63
  packages/imperative/__tests__/__snapshots__/LoggingConfigurer.test.ts.snap
  packages/logger/__tests__/__snapshots__/LoggerConfigBuilder.test.ts.snap
  packages/logger/src/LoggerConfigBuilder.ts
  packages/logger/src/doc/ILog4jsAppender.ts
Labels: in progress, review

#79 Don't fail build on npm audit vulnerabilities for now
  gulp/DevelopmentTasks.ts
Labels: in progress, review

#73 Fix/66
  __tests__/src/packages/imperative/plugins/suites/InstallingPlugins.ts
  __tests__/src/packages/imperative/plugins/suites/ValidatePlugin.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/index.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/index.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/index.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/bar/bar.handler.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/bar/bar.handler.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/bar/bar.handler.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/foo/foo.handler.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/foo/foo.handler.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/foo/foo.handler.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/healthCheck.handler.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/healthCheck.handler.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/healthCheck.handler.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/index.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/index.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/index.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/package.json
  packages/imperative/src/plugins/utilities/runValidatePlugin.ts
Labels: in progress, review

#72 Fix/1.0.0/66
  __tests__/src/packages/imperative/plugins/suites/InstallingPlugins.ts
  __tests__/src/packages/imperative/plugins/suites/ValidatePlugin.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/index.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/index.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/index.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/bar/bar.handler.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/bar/bar.handler.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/bar/bar.handler.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/foo/foo.handler.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/foo/foo.handler.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/cmd/foo/foo.handler.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/healthCheck.handler.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/healthCheck.handler.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/healthCheck.handler.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/index.d.ts
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/index.js
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/lib/sample-plugin/index.js.map
  __tests__/src/packages/imperative/plugins/test_plugins/space in path plugin/package.json
  package.json
  packages/imperative/src/plugins/utilities/runValidatePlugin.ts
Labels: in progress, review

#70 Remove node_report
  package-lock.json
  package.json
  packages/error/__tests__/ErrorReport.test.ts
  packages/error/__tests__/ImperativeError.test.ts
  packages/error/index.ts
  packages/error/src/ErrorReport.ts
  packages/error/src/ImperativeError.ts
  packages/error/src/doc/IErrorReportParms.ts
  packages/error/src/doc/IErrorSavedSettings.ts
  packages/error/src/doc/IImperativeErrorParms.ts
  packages/expect/src/ImperativeExpect.ts
  packages/imperative/src/Imperative.ts
  packages/security/src/DefaultCredentialManager.ts
Labels: in progress, review

#83 Enhancement/34
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/Cmd.cli.profile.option.mapping.integration.test.ts
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/banana_profile_and_specify_cli.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/banana_profile_and_specify_env.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/banana_profile_and_specify_env_and_cli.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/map_banana_to_options.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/map_banana_to_positionals.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/specify_env_for_array.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/specify_env_for_boolean.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/specify_env_for_number.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/specify_env_for_positional.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/specify_env_sweetness.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__snapshots__/Cmd.cli.root.test.ts.snap
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/cmd/src/cli/profile/ProfileMapping.definition.ts
  __tests__/__integration__/cmd/src/cli/profile/mapping-positional/ProfileMapping.definition.ts
  __tests__/__integration__/cmd/src/cli/profile/mapping-positional/ProfileMapping.handler.ts
  __tests__/__integration__/cmd/src/cli/profile/mapping/ProfileMapping.definition.ts
  __tests__/__integration__/cmd/src/cli/profile/mapping/ProfileMapping.handler.ts
  __tests__/__integration__/cmd/src/imperative/config.ts
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/imperative/package-lock.json
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  packages/cmd/__tests__/CommandProcessor.test.ts
  packages/cmd/__tests__/__model__/TestArgHandler.ts
  packages/cmd/__tests__/__snapshots__/CommandProcessor.test.ts.snap
  packages/cmd/index.ts
  packages/cmd/src/CommandPreparer.ts
  packages/cmd/src/CommandProcessor.ts
  packages/cmd/src/doc/args/ICommandArguments.ts
  packages/cmd/src/doc/handler/IHandlerParameters.ts
  packages/cmd/src/doc/processor/ICommandProcessorParms.ts
  packages/cmd/src/doc/response/response/ICommandPrepared.ts
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/cmd/src/syntax/SyntaxValidator.ts
  packages/cmd/src/utils/CommandUtils.ts
  packages/cmd/src/yargs/AbstractCommandYargs.ts
  packages/cmd/src/yargs/CommandYargs.ts
  packages/cmd/src/yargs/GroupCommandYargs.ts
  packages/cmd/src/yargs/YargsConfigurer.ts
  packages/cmd/src/yargs/YargsDefiner.ts
  packages/cmd/src/yargs/doc/IYargsParms.ts
  packages/imperative/src/Imperative.ts
  packages/profiles/src/doc/definition/IProfile.ts
  packages/utilities/__tests__/CliUtils.test.ts
  packages/utilities/__tests__/__snapshots__/CliUtils.test.ts.snap
  packages/utilities/src/CliUtils.ts
  packages/utilities/src/doc/IOptionFormat.ts
Labels: S3-18PI4, in progress, review

#90 Enhancement/71
  __tests__/__integration__/cmd/__tests__/integration/cli/validate/Cmd.cli.validate.test.ts
  __tests__/__integration__/cmd/__tests__/integration/cli/validate/__scripts__/invalid_positional1.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/validate/__snapshots__/Cmd.cli.validate.test.ts.snap
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/cmd/src/cli/validate/syntax/Syntax.definition.ts
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/imperative/package-lock.json
  package-lock.json
  packages/cmd/__tests__/CommandProcessor.test.ts
  packages/cmd/__tests__/__snapshots__/CommandProcessor.test.ts.snap
  packages/cmd/src/CommandProcessor.ts
  packages/cmd/src/syntax/SyntaxValidator.ts
  packages/cmd/src/syntax/__tests__/SyntaxValidator.test.ts
  packages/error/__tests__/ImperativeError.test.ts
Labels: enhancement, in progress, review

#97 Resolve the blocking portion of #96
  package-lock.json
  package.json
Labels: in progress, review
