Repository zowe/imperative, pull requests merged in 2018-11, with the labels that each got.

#94 Module Loader for Plugins
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__src__/decorators/MockMethod.ts
  __tests__/__src__/types/MockWrapper.ts
  __tests__/src/packages/imperative/plugins/PluginManagementFacility.spec.ts
  __tests__/src/packages/profiles/test_cli/package.json
  packages/imperative/__tests__/plugins/PluginManagementFacility.test.ts
  packages/imperative/__tests__/plugins/PluginRequireProvider.test.ts
  packages/imperative/__tests__/plugins/utilities/PMFConstants.test.ts
  packages/imperative/src/ImperativeConfig.ts
  packages/imperative/src/__mocks__/ImperativeConfig.ts
  packages/imperative/src/plugins/PluginManagementFacility.ts
  packages/imperative/src/plugins/PluginRequireProvider.ts
  packages/imperative/src/plugins/__mocks__/PluginRequireProvider.ts
  packages/imperative/src/plugins/errors/PluginRequireAlreadyCreatedError.ts
  packages/imperative/src/plugins/errors/PluginRequireNotCreatedError.ts
  packages/imperative/src/plugins/utilities/PMFConstants.ts
  packages/imperative/src/plugins/utilities/__mocks__/PMFConstants.ts
  packages/imperative/src/plugins/utilities/npm-interface/install.ts
  packages/imperative/src/plugins/utilities/runValidatePlugin.ts
  tsconfig.json
Labels: Major, enhancement, in progress, plugins, review

#95 Enhancement/91
  __tests__/__integration__/cmd/__tests__/integration/cli/validate/Cmd.cli.validate.test.ts
  __tests__/__integration__/cmd/__tests__/integration/cli/validate/__scripts__/string_or_blank_option.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/validate/__snapshots__/Cmd.cli.validate.test.ts.snap
  __tests__/__integration__/cmd/src/cli/validate/Validate.definition.ts
  __tests__/__integration__/cmd/src/cli/validate/string-or-empty/string-or-empty.definition.ts
  __tests__/__integration__/cmd/src/cli/validate/string-or-empty/string-or-empty.handler.ts
  packages/cmd/src/doc/option/ICommandOptionDefinition.ts
  packages/cmd/src/help/abstract/AbstractHelpGenerator.ts
  packages/cmd/src/syntax/SyntaxValidator.ts
  packages/io/__tests__/IO.test.ts
  packages/io/__tests__/__snapshots__/IO.test.ts.snap
  packages/io/src/IO.ts
Labels: in progress, review

#102 Removing outdated comment
  packages/imperative/src/plugins/utilities/npm-interface/update.ts
Labels: in progress, review

#103 Allow space for validate
  packages/imperative/src/plugins/utilities/runValidatePlugin.ts
Labels: in progress, review

#104 43 apiml integration
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/imperative/package-lock.json
  packages/cmd/src/CommandProcessor.ts
  packages/rest/__tests__/client/RestClient.test.ts
  packages/rest/__tests__/client/RestClientError.test.ts
  packages/rest/__tests__/client/__snapshots__/AbstractRestClient.test.ts.snap
  packages/rest/__tests__/client/__snapshots__/RestClientError.test.ts.snap
  packages/rest/__tests__/session/__snapshots__/Session.test.ts.snap
  packages/rest/index.ts
  packages/rest/src/client/AbstractRestClient.ts
  packages/rest/src/client/RestClientError.ts
  packages/rest/src/client/doc/IRestClientError.ts
  packages/rest/src/session/AbstractSession.ts
  packages/rest/src/session/doc/ISession.ts
Labels: review

#108 fix #107
  packages/imperative/src/doc/IImperativeOverrides.ts
  packages/security/src/CredentialManagerFactory.ts
Labels: in progress, review

#109 Enhancement/105
  __tests__/__integration__/cmd/__tests__/integration/cli/invoke/__snapshots__/Cmd.cli.invoke.test.ts.snap
  __tests__/__integration__/cmd/__tests__/integration/cli/nested/__snapshots__/Cmd.cli.nested.first-group.test.ts.snap
  __tests__/__integration__/cmd/__tests__/integration/cli/nested/__snapshots__/Cmd.cli.nested.test.ts.snap
  __tests__/__integration__/cmd/__tests__/integration/cli/respond/__snapshots__/Cmd.cli.respond.test.ts.snap
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__snapshots__/Cmd.cli.root.test.ts.snap
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/hello_world/__test__/__snapshots__/HelloWorldCli.test.ts.snap
  __tests__/__integration__/imperative/__tests__/__integration__/cli/test/__snapshots__/cli.imperative-test-cli.test.integration.test.ts.snap
  __tests__/__integration__/imperative/package-lock.json
  packages/cmd/__tests__/help/__snapshots__/DefaultHelpGenerator.test.ts.snap
  packages/cmd/src/help/DefaultHelpGenerator.ts
Labels: CA - 18PI4, S5-18PI4, in progress, review

#116 Fix/101 111
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/imperative/package-lock.json
  package-lock.json
  package.json
  packages/imperative/__tests__/plugins/cmd/install/install.handler.test.ts
  packages/imperative/__tests__/plugins/cmd/update/update.handler.test.ts
  packages/imperative/__tests__/plugins/utilities/npm-interface/install.test.ts
  packages/imperative/__tests__/plugins/utilities/npm-interface/uninstall.test.ts
  packages/imperative/__tests__/plugins/utilities/npm-interface/update.test.ts
  packages/imperative/src/plugins/cmd/install/install.definition.ts
  packages/imperative/src/plugins/cmd/install/install.handler.ts
  packages/imperative/src/plugins/cmd/update/update.definition.ts
  packages/imperative/src/plugins/cmd/update/update.handler.ts
  packages/imperative/src/plugins/utilities/NpmApiFunctions.ts
  packages/imperative/src/plugins/utilities/NpmFunctions.ts
  packages/imperative/src/plugins/utilities/npm-interface/install.ts
  packages/imperative/src/plugins/utilities/npm-interface/uninstall.ts
  packages/imperative/src/plugins/utilities/npm-interface/update.ts
Labels: Minor, in progress, plugins, review

#117 Log diagnostic messages when errors are encountered
  __tests__/__integration__/hello_world/package-lock.json
  packages/cmd/src/CommandProcessor.ts
  packages/imperative/src/Imperative.ts
Labels: in progress, review

#119 fix pkg bug, so now it finds node-gyp and npm modules in parent cli d…
  package.json
Labels: in progress, review

#120 Eliminate name and type from loaded profiles
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/Cmd.cli.profile.option.mapping.integration.test.ts
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/name_type_specify.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/name_type_undefined.sh
  __tests__/__integration__/cmd/src/cli/profile/ProfileMapping.definition.ts
  __tests__/__integration__/cmd/src/cli/profile/mapping-name-type/ProfileMappingNameType.definition.ts
  __tests__/__integration__/cmd/src/cli/profile/mapping-name-type/ProfileMappingNameType.handler.ts
  __tests__/src/example_clis/with_profiles/AutoGeneratedProfileCommands.spec.ts
  __tests__/src/example_clis/with_profiles/handlers/UseDependentProfileHandler.ts
  __tests__/src/packages/cmd/profiles/CliProfileManager.test.ts
  __tests__/src/packages/imperative/plugins/suites/UsingPlugins.ts
  __tests__/src/packages/profiles/BasicProfileManager.spec.ts
  __tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts
  __tests__/src/packages/profiles/__snapshots__/BasicProfileManager.spec.ts.snap
  package-lock.json
  packages/cmd/__tests__/profiles/CliProfileManager.credentials.test.ts
  packages/cmd/__tests__/profiles/CliProfileManager.test.ts
  packages/cmd/__tests__/profiles/CommandProfiles.test.ts
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/cmd/src/profiles/CommandProfiles.ts
  packages/imperative/__tests__/profiles/handlers/__snapshots__/ListProfilesHandler.test.ts.snap
  packages/imperative/src/profiles/handlers/CreateProfilesHandler.ts
  packages/imperative/src/profiles/handlers/ListProfilesHandler.ts
  packages/profiles/__tests__/BasicProfileManager.load.test.ts
  packages/profiles/__tests__/BasicProfileManager.merge.test.ts
  packages/profiles/__tests__/BasicProfileManager.save.test.ts
  packages/profiles/__tests__/BasicProfileManager.update.test.ts
  packages/profiles/__tests__/BasicProfileManager.validate.test.ts
  packages/profiles/__tests__/__snapshots__/BasicProfileManager.load.test.ts.snap
  packages/profiles/__tests__/__snapshots__/BasicProfileManager.save.test.ts.snap
  packages/profiles/__tests__/__snapshots__/BasicProfileManager.test.ts.snap
  packages/profiles/src/BasicProfileManager.ts
  packages/profiles/src/abstract/AbstractProfileManager.ts
  packages/profiles/src/doc/definition/IProfile.ts
  packages/profiles/src/doc/parms/ISaveProfile.ts
  packages/profiles/src/doc/parms/IValidateProfile.ts
  packages/profiles/src/utils/ProfileIO.ts
Labels: in progress, review

#124 35 improve syntax error message
  .gitignore
  __tests__/__integration__/cmd/__tests__/integration/cli/root/Cmd.cli.root.test.ts
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__scripts__/invalid_command.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__scripts__/invalid_command2.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__snapshots__/Cmd.cli.root.test.ts.snap
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/imperative/package-lock.json
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  __tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts
  package-lock.json
  package.json
  packages/cmd/src/CommandProcessor.ts
  packages/cmd/src/doc/processor/ICommandProcessorParms.ts
  packages/cmd/src/yargs/AbstractCommandYargs.ts
  packages/cmd/src/yargs/CommandYargs.ts
  packages/cmd/src/yargs/GroupCommandYargs.ts
  packages/cmd/src/yargs/YargsConfigurer.ts
  packages/cmd/src/yargs/YargsDefiner.ts
  packages/cmd/src/yargs/doc/IYargsParms.ts
  packages/imperative/src/Imperative.ts
Labels: in progress, review

#125 Add expectBuffer methods to restclient for 1.0.0 branch
  __tests__/src/TestUtil.ts
  packages/rest/__tests__/client/RestClient.test.ts
  packages/rest/src/client/RestClient.ts
Labels: in progress, review

#129 update imperative version in package.json in 1.0.0 branch for expectBuffer changes
  package.json
Labels: in progress, review
