Repository zowe/imperative, pull requests merged in 2019-07, with the labels that each got.

#247 Package.json update
  gulp/SampleCliAndPlugin.ts
  package.json
  packages/error/src/ImperativeError.ts
Labels: release-patch

#232 Prevent truncation of last character of cookie element.
  packages/rest/__tests__/session/__snapshots__/Session.test.ts.snap
  packages/rest/src/session/AbstractSession.ts
Labels: needs-ported, release-patch

#254 Update software req for Python/C++ Compiler
  README.md
Labels: documentation, no-release
