Repository zowe/imperative, pull requests merged in 2019-04, with the labels that each got.

#193 Enable masked prompting for arguments
  __tests__/__integration__/cmd/__tests__/integration/cli/prompting/__scripts__/prompt_for_color.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/prompting/cli.prompting.integration.test.ts
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/cmd/package.json
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/hello_world/package.json
  __tests__/__integration__/imperative/__tests__/__integration__/api/env/__snapshots__/EnvironmentalVariableSettings.integration.test.ts.snap
  __tests__/__integration__/imperative/__tests__/beforeTests.js
  __tests__/__integration__/imperative/package-lock.json
  __tests__/__integration__/imperative/package.json
  __tests__/config/integration/jest.config.json
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  __tests__/src/packages/imperative/ConfigLoading.spec.ts
  __tests__/src/packages/imperative/plugins/suites/UsingPlugins.ts
  __tests__/src/packages/profiles/BasicProfileManager.spec.ts
  __tests__/src/packages/profiles/__snapshots__/BasicProfileManager.initialize.spec.ts.snap
  __tests__/src/packages/profiles/test_cli/customCredential/CustomCredentialManager.ts
  __tests__/src/packages/profiles/test_cli/customCredential/CustomCredentialManagerClass.ts
  doc/ManualTestPrompting.md
  gulp/TestTasks.ts
  package.json
  packages/cmd/__tests__/CommandProcessor.test.ts
  packages/cmd/src/CommandProcessor.ts
  packages/cmd/src/doc/processor/ICommandProcessorParms.ts
  packages/cmd/src/yargs/AbstractCommandYargs.ts
  packages/cmd/src/yargs/CommandYargs.ts
  packages/cmd/src/yargs/GroupCommandYargs.ts
  packages/cmd/src/yargs/YargsConfigurer.ts
  packages/cmd/src/yargs/YargsDefiner.ts
  packages/cmd/src/yargs/doc/IYargsParms.ts
  packages/constants/src/Constants.ts
  packages/imperative/__tests__/LoggingConfigurer.test.ts
  packages/imperative/__tests__/__snapshots__/LoggingConfigurer.test.ts.snap
  packages/imperative/__tests__/env/__snapshots__/EnvironmentalVariableSettings.test.ts.snap
  packages/imperative/src/Imperative.ts
  packages/imperative/src/doc/IImperativeEnvironmentalVariableSettings.ts
  packages/imperative/src/env/EnvironmentalVariableSettings.ts
  packages/logger/__tests__/Logger.test.ts
  packages/logger/__tests__/LoggerConfigBuilder.test.ts
  packages/logger/__tests__/__snapshots__/LoggerConfigBuilder.test.ts.snap
  packages/utilities/__tests__/CliUtils.test.ts
  packages/utilities/src/CliUtils.ts
  sonar-project.properties
Labels: in progress, release-major, review

#195 Fix #54 where 0 could not be specified for positionals (lts-incremental)
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  packages/cmd/src/syntax/SyntaxValidator.ts
Labels: in progress, release-patch, review

#196 Fix #54 where 0 could not be specified for positionals
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  packages/cmd/src/syntax/SyntaxValidator.ts
Labels: in progress, release-patch, review

#198 Add afterAll to delete package.json file to avoid error running integ…
  __tests__/src/packages/imperative/ConfigLoading.spec.ts
Labels: in progress, no-release, review

#199 Add streaming APIs to Rest client
  package.json
  packages/io/__tests__/IO.test.ts
  packages/io/__tests__/__snapshots__/IO.test.ts.snap
  packages/io/src/IO.ts
  packages/rest/__tests__/client/AbstractRestClient.test.ts
  packages/rest/src/client/AbstractRestClient.ts
  packages/rest/src/client/RestClient.ts
Labels: in progress, release-minor, review

#201 Introduce streaming rest client methods (lts-incremental)
  package.json
  packages/io/__tests__/IO.test.ts
  packages/io/__tests__/__snapshots__/IO.test.ts.snap
  packages/io/src/IO.ts
  packages/rest/__tests__/client/AbstractRestClient.test.ts
  packages/rest/src/client/AbstractRestClient.ts
  packages/rest/src/client/RestClient.ts
Labels: in progress, release-minor, review

#204 Move vulnerability check later in the build so that tests can still run if the check fails
  Jenkinsfile
Labels: in progress, review

#205 Move vulnerability check later in the build so that tests can still run (lts incremental)
  Jenkinsfile
Labels: in progress, review

#203 Escape special characters when generating Markdown, fix #202
  packages/cmd/__tests__/help/DefaultHelpGenerator.test.ts
  packages/cmd/__tests__/help/__snapshots__/DefaultHelpGenerator.test.ts.snap
  packages/cmd/src/help/DefaultHelpGenerator.ts
Labels: in progress, release-patch, review

#206 Port #203 to lts-incremental
  packages/cmd/__tests__/help/DefaultHelpGenerator.test.ts
  packages/cmd/__tests__/help/__snapshots__/DefaultHelpGenerator.test.ts.snap
  packages/cmd/src/help/DefaultHelpGenerator.ts
Labels: in progress, review
