Repository zowe/imperative, pull requests merged in 2019-02, with the labels that each got.

#153 Posix.Normalize the output path
  packages/rest/src/client/AbstractRestClient.ts
Labels: in progress, review

#160 update version
  .gitignore
  .npmrc
  package-lock.json
  package.json
Labels: in progress, review

#162 Fix issue where required array type positionals could not be validated
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  package.json
  packages/cmd/src/syntax/SyntaxValidator.ts
Labels: in progress, review

#166 Zowe/zowe cli/142
  .gitignore
  .vscode/launch.json
  Jenkinsfile
  __tests__/__integration__/cmd/__tests__/integration/cli/chained/Cmd.cli.chainedhandlers.test.ts
  __tests__/__integration__/imperative/__tests__/__integration__/api/env/EnvironmentalVariableSettings.integration.test.ts
  __tests__/config/debug/jest.config.json
  __tests__/config/integration/.env.js
  __tests__/config/integration/jest.config.json
  __tests__/config/jest.preset.json
  __tests__/config/unit/.env.js
  __tests__/config/unit/jest.config.json
  gulp/TestTasks.ts
  package.json
  packages/cmd/__tests__/help/__snapshots__/AbstractHelpGenerator.test.ts.snap
  packages/imperative/__tests__/Imperative.test.ts
  packages/imperative/__tests__/OverridesLoader.test.ts
  packages/imperative/__tests__/plugins/utilities/runValidatePlugin.test.ts
  packages/rest/__tests__/client/RestClient.test.ts
  packages/rest/__tests__/client/__snapshots__/RestClient.test.ts.snap
  packages/rest/src/client/AbstractRestClient.ts
Labels: in progress, review

#165 User masking
  .gitignore
  packages/cmd/src/CommandProcessor.ts
Labels: in progress, release-minor, review

#168 Allow a blank file to be written with IO.writeFileAsync
  packages/io/__tests__/__snapshots__/IO.test.ts.snap
  packages/io/src/IO.ts
Labels: release-patch, review

#171 Remove unused @types/lodash
  package.json
Labels: in progress, release-patch, review

#170 Enhancement/130
  .npmrc
  Jenkinsfile
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/cmd/package.json
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/hello_world/package.json
  __tests__/__integration__/imperative/package-lock.json
  __tests__/__integration__/imperative/package.json
  gulp/DevelopmentTasks.ts
  jenkins/npm_login_zowe.expect
  package.json
  packages/cmd/src/CommandProcessor.ts
  packages/imperative/src/Imperative.ts
  packages/imperative/src/config/ConfigManagementFacility.ts
  packages/imperative/src/plugins/PluginManagementFacility.ts
  packages/imperative/src/plugins/PluginRequireProvider.ts
  packages/logger/__tests__/Logger.test.ts
  packages/logger/src/Logger.ts
  packages/logger/src/LoggerManager.ts
  packages/rest/src/client/AbstractRestClient.ts
  packages/security/__tests__/CredentialManagerFactory-testClasses/GoodCredentialManager.ts
Labels: in progress, release-major, review

#172 Fix master
  .npmrc
  Jenkinsfile
  package.json
Labels: in progress, release-patch, review

#174 Add ability to specify "prefix" on ICommandExampleDefinition interface
  __tests__/__integration__/cmd/__tests__/integration/cli/gen-help/__snapshots__/Cmd.cli.gen-help.example-test.integration.test.ts.snap
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/cmd/src/cli/gen-help/example-test/ExampleTest.definition.ts
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/__integration__/imperative/package-lock.json
  packages/cmd/src/doc/ICommandExampleDefinition.ts
  packages/cmd/src/help/DefaultHelpGenerator.ts
Labels: in progress, release-minor, review

#175 Fix deploy
  Jenkinsfile
Labels: in progress, release-patch, review

#173 Check that tests compile during build
  Jenkinsfile
  __tests__/src/packages/profiles/src/constants/BasicProfileManagerTestContants.ts
  package.json
  packages/cmd/__tests__/ChainedHandlerUtils.test.ts
  packages/cmd/__tests__/CommandProcessor.test.ts
  packages/cmd/__tests__/__snapshots__/CommandResponse.test.ts.snap
  packages/cmd/__tests__/__snapshots__/CommandUtils.test.ts.snap
  packages/cmd/__tests__/__snapshots__/DefaultRootCommandHandler.test.ts.snap
  packages/cmd/__tests__/__snapshots__/FailedCommandHandler.test.ts.snap
  packages/cmd/__tests__/__snapshots__/SharedOptions.test.ts.snap
  packages/expect/__tests__/ImperativeExpect.test.ts
  packages/expect/__tests__/__snapshots__/ImperativeExpect.test.ts.snap
  packages/io/__tests__/IO.test.ts
  packages/logger/__tests__/Logger.test.ts
  packages/profiles/__tests__/BasicProfileManager.save.test.ts
  packages/profiles/__tests__/BasicProfileManager.test.ts
  packages/profiles/__tests__/BasicProfileManager.validate.test.ts
  packages/profiles/src/utils/__tests__/ProfileIO.test.ts
  packages/profiles/src/utils/__tests__/ProfileUtils.test.ts
  packages/security/__tests__/CredentialManagerFactory.test.ts
  packages/settings/__tests__/AppSettings.test.ts
  tsconfig-tests.json
Labels: in progress, release-patch, review
