Repository zowe/imperative, pull requests merged in 2019-05, with the labels that each got.

#208 Markdown help generator fixes
  packages/cmd/src/help/DefaultHelpGenerator.ts
Labels: in progress, release-patch, review

#209 Markdown fixes lts-incremental
  packages/cmd/src/help/DefaultHelpGenerator.ts
Labels: in progress, release-patch, review

#214 add simple flow diagram
  doc/Imperative_CLI_Flow.png
Labels: in progress, no-release, review

#211 Fix typo in positional argument comment
  packages/cmd/src/doc/option/ICommandPositionalDefinition.ts
Labels: in progress, no-release, review

#212 Fix typo in positional argument comment - lts incremental
  packages/cmd/src/doc/option/ICommandPositionalDefinition.ts
Labels: in progress, no-release, review

#215 Address vulnerabilities
  .gitignore
  .npmrc
  Jenkinsfile
  npm-shrinkwrap.json
  package.json
Labels: release-patch
