Repository zowe/imperative, pull requests merged in 2019-01, with the labels that each got.

#137 Render emails as HTML
  Jenkinsfile
Labels: in progress, review

#138 Export HTTPVerb from rest package
  packages/rest/index.ts
Labels: in progress, review

#135 Display available commands
  __tests__/__integration__/cmd/__tests__/integration/cli/root/Cmd.cli.root.test.ts
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__scripts__/available_commands.sh
  __tests__/__integration__/cmd/__tests__/integration/cli/root/__snapshots__/Cmd.cli.root.test.ts.snap
  __tests__/__integration__/hello_world/__test__/__snapshots__/HelloWorldCli.test.ts.snap
  __tests__/__integration__/hello_world/package.json
  package-lock.json
  packages/imperative/__tests__/handlers/DefaultRootCommandHandler.test.ts
  packages/imperative/__tests__/handlers/__snapshots__/DefaultRootCommandHandler.test.ts.snap
  packages/imperative/src/DefinitionTreeResolver.ts
  packages/imperative/src/__mocks__/Imperative.ts
  packages/imperative/src/handlers/DefaultRootCommandHandler.ts
Labels: in progress, review

#140 Fix problem with validate profile command
  __tests__/src/example_clis/with_profiles/AutoGeneratedProfileCommands.spec.ts
  package-lock.json
  packages/cmd/__tests__/profiles/builders/__snapshots__/CompleteProfilesGroupBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesValidateCommandBuilder.test.ts.snap
  packages/imperative/src/profiles/builders/ProfilesValidateCommandBuilder.ts
  packages/imperative/src/profiles/handlers/ValidateProfileHandler.ts
  packages/profiles/src/validation/__tests__/ProfileValidation.spec.ts
  packages/profiles/src/validation/api/ProfileValidator.ts
Labels: in progress, review

#144 fix repository in package.json
  package.json
Labels: in progress, review

#145 Add examples to profile commands
  .gitignore
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/src/example_clis/with_profiles/AutoGeneratedProfileCommands.spec.ts
  __tests__/src/example_clis/with_profiles/ProfileExampleConfiguration.ts
  packages/cmd/__tests__/profiles/CliProfileManager.credentials.test.ts
  packages/cmd/__tests__/profiles/CliProfileManager.test.ts
  packages/cmd/__tests__/profiles/builders/__snapshots__/CompleteProfilesGroupBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesDeleteCommandBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesListCommandBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesSetCommandBuilder.test.ts.snap
  packages/cmd/src/doc/profiles/definition/ICommandProfileTypeConfiguration.ts
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/imperative/src/profiles/builders/ProfilesDeleteCommandBuilder.ts
  packages/imperative/src/profiles/builders/ProfilesListCommandBuilder.ts
  packages/imperative/src/profiles/builders/ProfilesSetCommandBuilder.ts
  packages/imperative/src/profiles/builders/ProfilesUpdateCommandBuilder.ts
  packages/messages/src/CoreMessages.ts
Labels: in progress, release-minor, review

#146 Fix issue where profile name is not displayed when a secure field fails to save
  __tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/profiles/src/validation/api/ProfileValidator.ts
Labels: in progress, release-patch, review

#148 Update jenkinsfile to accommodate all deployment
  Jenkinsfile
  package.json
Labels: in progress, review

#150 Command processor fixes
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  packages/cmd/__tests__/CommandProcessor.test.ts
  packages/cmd/src/CommandProcessor.ts
Labels: in progress, review

#151 Merge master into beta
  .gitignore
  Jenkinsfile
  __tests__/__integration__/cmd/package-lock.json
  __tests__/__integration__/hello_world/package-lock.json
  __tests__/src/example_clis/with_profiles/AutoGeneratedProfileCommands.spec.ts
  __tests__/src/example_clis/with_profiles/ProfileExampleConfiguration.ts
  __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts
  __tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts
  package-lock.json
  package.json
  packages/cmd/__tests__/CommandProcessor.test.ts
  packages/cmd/__tests__/profiles/CliProfileManager.credentials.test.ts
  packages/cmd/__tests__/profiles/CliProfileManager.test.ts
  packages/cmd/__tests__/profiles/builders/__snapshots__/CompleteProfilesGroupBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesDeleteCommandBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesListCommandBuilder.test.ts.snap
  packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesSetCommandBuilder.test.ts.snap
  packages/cmd/src/CommandProcessor.ts
  packages/cmd/src/doc/profiles/definition/ICommandProfileTypeConfiguration.ts
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/imperative/src/profiles/builders/ProfilesDeleteCommandBuilder.ts
  packages/imperative/src/profiles/builders/ProfilesListCommandBuilder.ts
  packages/imperative/src/profiles/builders/ProfilesSetCommandBuilder.ts
  packages/imperative/src/profiles/builders/ProfilesUpdateCommandBuilder.ts
  packages/messages/src/CoreMessages.ts
  packages/profiles/src/validation/api/ProfileValidator.ts
Labels: in progress, review

#152 Update Jenkinsfile
  Jenkinsfile
Labels: in progress, review

#155 Update jenkinsfile
  Jenkinsfile
  package.json
Labels: in progress, review

#156 Update incremental
  Jenkinsfile
  package.json
Labels: in progress, review

#157 Fix all other master-only assumptions
  Jenkinsfile
Labels: in progress, review

#158 Fix all other master-only assumptions [ci skip]
  Jenkinsfile
Labels: in progress, review

#154 Merge master into beta
  Jenkinsfile
  package-lock.json
  package.json
Labels: in progress, review

#159 Update stable
  Jenkinsfile
  package.json
Labels: in progress, review
