Repository zowe/imperative, pull requests merged in 2019-03, with the labels that each got.

#181 output plugins object in data field on plugins list --rfj
  packages/imperative/__tests__/plugins/cmd/list/list.handler.test.ts
  packages/imperative/src/plugins/cmd/list/list.handler.ts
Labels: in progress, release-patch, review

#184 Update jenkinsfile in LTS incremental
  Jenkinsfile
Labels: in progress, release-minor, review

#186 add summary to config group for shorter top level help
  packages/imperative/src/config/ConfigManagementFacility.ts
Labels: in progress, release-patch, review

#188 Fix vulnerabilites
  .gitignore
  package.json
Labels: in progress, review

#191 revert typescript version
  package.json
Labels: in progress, release-patch, review
