Repository zowe/imperative, pull requests merged in 2022-08, with the labels that each got.

#872 Fix automatic link detection in web help
  CHANGELOG.md
  packages/cmd/__tests__/help/WebHelpGenerator.test.ts
  packages/cmd/src/help/WebHelpGenerator.ts
Labels: needs-ported

#873 Revert Node lockdown in workflows
  .github/workflows/imperative.yml
  packages/config/__tests__/ProfileInfo.TeamConfig.test.ts
Labels: needs-ported, no-changelog

#879 [Backport] Fix code smells
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/cmd/src/response/CommandResponse.ts
Labels: no-changelog

#878 Fix code smells
  packages/cmd/src/profiles/CliProfileManager.ts
  packages/cmd/src/response/CommandResponse.ts
  packages/config/src/ConfigAutoStore.ts
  packages/config/src/ConfigSchema.ts
  packages/config/src/ProfileInfo.ts
  packages/imperative/src/auth/handlers/BaseAuthHandler.ts
  packages/utilities/__tests__/diff/WebDiffManager.test.ts
Labels: no-changelog
